### ISSUE TITLE
Settings for Policies

### ISSUE THREAD

**Issue by spottedmahn** [yoelhor/aad-b2c-vs-code-extension#2]
What about something in this tool to supplement the lack of support for settings in custom policies?

- change tenant name
- set client_id and IdTokenAudience

[UserVoice item](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/33150472-settings-in-custom-policies)

**Comment by yoelhor** [comment]
This feature has been added. For more information see the readme file

**Comment by spottedmahn** [comment]
Nice 👍!

Readme link: [App Settings](https://github.com/yoelhor/aad-b2c-vs-code-extension#app-settings)

**Comment by yoelhor** [comment]
Thanks, I updated the readme file today with more information
