### ISSUE TITLE
Restful Provider Template updates incorrect Key for AuthenticationType

### ISSUE THREAD

**Issue by WhippsP** [yoelhor/aad-b2c-vs-code-extension#4]
On creation of a Restful Provider (>B2C Add REST API technical profile) if you change the Authentication type to anything other than None it will update the value in the SendClaimsIn Key, eg:

	    
	    <TechnicalProfile Id="TEST">
	        <DisplayName>Validate user input data and return loyaltyNumber claim</DisplayName>
	        <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
	        <Metadata>
	        <Item Key="ServiceUrl">http://testurl.com,</Item>
	        <Item Key="AuthenticationType">None</Item>
	        <Item Key="SendClaimsIn">Basic</Item>
	        </Metadata>
	        <CryptographicKeys>
	             <Key Id="BasicAuthenticationUsername" StorageReferenceId="B2C_1A_B2cRestClientId" />
	             <Key Id="BasicAuthenticationPassword" StorageReferenceId="B2C_1A_B2cRestClientSecret" />
	        </CryptographicKeys>
	        <InputClaims>
	        <InputClaim ClaimTypeReferenceId="email" />
	        <InputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="firstName" />
	        <InputClaim ClaimTypeReferenceId="surname" PartnerClaimType="lastName" />
	        </InputClaims>
	        <OutputClaims>
	        <OutputClaim ClaimTypeReferenceId="loyaltyNumber" PartnerClaimType="loyaltyNumber" />
	        </OutputClaims>
	        <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />
	    </TechnicalProfile>

**Comment by WhippsP** [comment]
I have Created a Pull Request for this Issue

**Comment by yoelhor** [comment]
Merged. Thank you so much for taking time and providing probable solution
